Fix OSS builds after 3.14 import
Summary:
3.14 upstream has changed `_Py_Instrumentation_GetLine` resulting in:
```
In file included from /home/runner/work/cinderx/cinderx/cinderx/UpstreamBorrow/borrowed-3.14.gen_cached.c:13:
/home/runner/work/cinderx/cinderx/cinderx/../cinderx/UpstreamBorrow/borrowed.h:83:37: error: conflicting types for ‘_Ci_Instrumentation_GetLine’; have ‘int(PyCodeObject *, _PyCoLineInstrumentationData *, int)’
   83 | #define _Py_Instrumentation_GetLine _Ci_Instrumentation_GetLine
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/cinderx/cinderx/cinderx/UpstreamBorrow/borrowed-3.14.gen_cached.c:4854:1: note: in expansion of macro ‘_Py_Instrumentation_GetLine’
 4854 | _Py_Instrumentation_GetLine(PyCodeObject *code, _PyCoLineInstrumentationData *line_data, int index)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/cinderx/cinderx/cinderx/../cinderx/UpstreamBorrow/borrowed.h:83:37: note: previous declaration of ‘_Ci_Instrumentation_GetLine’ with type ‘int(PyCodeObject *, int)’
   83 | #define _Py_Instrumentation_GetLine _Ci_Instrumentation_GetLine
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We don't actually call this externally, we just need it as a dependency to other instrumentation functions. Let's just put the redefine in the borrowed file so we don't hit errors.

Reviewed By: grantlouisherman

Differential Revision: D103439294

fbshipit-source-id: 4c65a1aa0870105590d906dd208345b950d9ba6f